name: pre_pr_checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Package deprecated — no lint or tests."
